# Spl
[[lst_list]]
weight = 1.0
name = "Jito Staked SOL"
symbol = "JitoSOL"
mint = "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = "https://storage.googleapis.com/token-metadata/JitoSOL-256.png"
[lst_list.pool]
program = "Spl"
pool = "Jito4APyf642JPZPx3hGc6WWJ8zPKtRbRs4P815Awbb"
validator_list = "3R3nGZpQs2aZo5FDQvd2MUQ6R7KhAPainds6uT6uE2mn"

[[lst_list]]
weight = 1.0
name = "Marinade staked SOL"
symbol = "mSOL"
mint = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So/logo.png"
[lst_list.pool]
program = "Marinade"

[[lst_list]]
weight = 0.0
name = "SOL"
symbol = "SOL"
mint = "So11111111111111111111111111111111111111112"
decimals = 9
token_program = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
logo_uri = "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/So11111111111111111111111111111111111111112/logo.png"
[lst_list.pool]
program = "ReservePool"
